### ISSUE TITLE
Change Link

### ISSUE THREAD

**Issue by JBlond** [DigiLive/jQuery-Merge-for-php-diff#10]
The example link in the description you point to http://digilive.github.io/jQuery-Merge-for-php-diff/

**Comment by JBlond** [comment]
![link](https://user-images.githubusercontent.com/2391810/155973773-619b8772-99e4-4bae-af78-14738adeb899.png)

**Comment by DigiLive** [comment]
I've changed the about section.

**Comment by JBlond** [comment]
:)
