### ISSUE TITLE
Transfer Ownership

### ISSUE THREAD

**Issue by DigiLive** [DigiLive/jQuery-Merge-for-php-diff#7]
I'm one of the main contributors of a php-diff fork at https://github.com/JBlond/php-diff.
This fork is still evolving and a lot of things has been changed since the last time you've updated this/your repository.
We do like your plugin and we would like our library and your plugin to be compatible with each other.

Since your last commit to this repository was 6 years ago, it looks like you've "abandoned" it.
Would you please consider to transfer the ownership of this repository to me?

This way I can update and maintain it.

**Comment by Xiphe** [comment]
Hey @DigiLive 

Cool to hear that there are active forks of php-diff!
In the past I considered working on this but it didn't felt rewarding since the php-diff seemed abandoned to me.

Honestly: I'd like to keep this project in my scope since it has some of the most starts for s.th. I created myself. 

I'll try to find time to update the lib to your fork and also work on what I wanted to do for a long time:

 - move the lib to plain javascript
 - add tests

I'd happily accept PRs and get more involved in the eco-system

**Comment by DigiLive** [comment]
Not a problem at all.
I'm already happy I've motivated you to start maintaining it again. 😊

We've recently enabled the wiki for our fork. It's yet to be filled, but in there we'd like to describe the different options, inputs and outputs which are available.
Keep an eye on it.

**Comment by Xiphe** [comment]
@DigiLive cool!

One thing I was quite unhappy with in the past was the need to move both sources into the frontend in order to resolve the conflict.

Does php-diff support some kind of patch format that I could produce in frontend rather then resolving with the complete final file?

**Comment by DigiLive** [comment]
The lib includes several text renderers which you can use to indentify the difference.

Another way to identify the differences is to call `Diff::getGroupedOpCodes()` or to create your own renderer.

If you can provide a standardized spec which is suitable for you, don't hesitate to create an issue for requesting another renderer.

**Comment by Xiphe** [comment]
Hey, @DigiLive 

I just stubled upon this again and If you're still interested I'd pass this project over

**Comment by JBlond** [comment]
@Xiphe We are still interested in this. it is a very fine addition to the php-diff project.

**Comment by DigiLive** [comment]
Still interested indeed.
I'm looking forward to it so we can try to revive the repo.

Thank you.

**Comment by Xiphe** [comment]
So who would be ne new owner?

**Comment by DigiLive** [comment]
As the first requester, I'd like to be the new owner.
But I'll add Mario as contribute anyway.

**Comment by Xiphe** [comment]
I initiated the transfer

**Comment by DigiLive** [comment]
Accepted.
Thank you very much and good luck with your other projects.

**Comment by Xiphe** [comment]
Thank you. Wish you all the best, too. Would appreciate if you'd keep my mentioned in the readme or so :)

**Comment by JBlond** [comment]
Sure, we will do that!
